-- =====================================================================
-- CIT 406 - Database Design (Fall "A" 2026)
-- Term Project: Multi-Vendor E-Commerce Marketplace
-- schema.sql  -  Physical schema (PostgreSQL 15+ / Supabase)
-- Author : Waqar Javed (250305023)
--
-- Implements the BCNF design from Module 3 (Project Logical Design).
-- Running this file rebuilds the whole schema from nothing; run
-- seed.sql afterwards to load sample data.
--
-- Referential actions are written out explicitly on every foreign key.
-- The business rule behind each one is in the comment above it and in
-- README.md.
-- =====================================================================

DROP SCHEMA IF EXISTS marketplace CASCADE;
CREATE SCHEMA marketplace;
SET search_path TO marketplace;


-- ---------------------------------------------------------------------
-- CATEGORY
-- ---------------------------------------------------------------------
CREATE TABLE category (
    category_id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    category_name  VARCHAR(60) NOT NULL,
    CONSTRAINT category_pk      PRIMARY KEY (category_id),
    CONSTRAINT category_name_uq UNIQUE (category_name)
);


-- ---------------------------------------------------------------------
-- SELLER
-- ---------------------------------------------------------------------
CREATE TABLE seller (
    seller_id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    business_name    VARCHAR(120) NOT NULL,
    contact_email    VARCHAR(254) NOT NULL,
    phone            VARCHAR(20),
    approval_status  VARCHAR(12)  NOT NULL DEFAULT 'pending',
    CONSTRAINT seller_pk       PRIMARY KEY (seller_id),
    CONSTRAINT seller_email_uq UNIQUE (contact_email),
    CONSTRAINT seller_status_ck
        CHECK (approval_status IN ('pending', 'approved', 'suspended', 'rejected'))
);


-- ---------------------------------------------------------------------
-- CUSTOMER
-- ---------------------------------------------------------------------
CREATE TABLE customer (
    customer_id  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    first_name   VARCHAR(50)  NOT NULL,
    last_name    VARCHAR(50)  NOT NULL,
    email        VARCHAR(254) NOT NULL,
    phone        VARCHAR(20),
    CONSTRAINT customer_pk       PRIMARY KEY (customer_id),
    CONSTRAINT customer_email_uq UNIQUE (email)
);


-- ---------------------------------------------------------------------
-- ADDRESS
-- Rows used by an order are write-once; an edited or removed address
-- is retired with is_active = FALSE instead of being changed.
-- ---------------------------------------------------------------------
CREATE TABLE address (
    address_id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    customer_id  INTEGER      NOT NULL,
    label        VARCHAR(30),
    street       VARCHAR(120) NOT NULL,
    city         VARCHAR(60)  NOT NULL,
    state        CHAR(2)      NOT NULL,
    postal_code  VARCHAR(10)  NOT NULL,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT address_pk          PRIMARY KEY (address_id),
    CONSTRAINT address_state_ck    CHECK (state ~ '^[A-Z]{2}$'),
    CONSTRAINT address_postal_ck   CHECK (postal_code ~ '^[0-9]{5}(-[0-9]{4})?$'),
    -- Rule: an address book belongs to its customer. Deleting a customer
    -- removes their saved addresses; the RESTRICT on order_header.address_id
    -- still blocks the delete if any of those addresses was shipped to.
    CONSTRAINT address_customer_fk FOREIGN KEY (customer_id)
        REFERENCES customer (customer_id)
        ON DELETE CASCADE ON UPDATE NO ACTION
);


-- ---------------------------------------------------------------------
-- PRODUCT
-- ---------------------------------------------------------------------
CREATE TABLE product (
    product_id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    seller_id     INTEGER       NOT NULL,
    category_id   INTEGER       NOT NULL,
    product_name  VARCHAR(150)  NOT NULL,
    description   TEXT,
    base_price    NUMERIC(10,2) NOT NULL,
    CONSTRAINT product_pk       PRIMARY KEY (product_id),
    CONSTRAINT product_price_ck CHECK (base_price >= 0),
    -- Rule: a seller who has listed products cannot be deleted; they are
    -- suspended through approval_status so their catalog history remains.
    CONSTRAINT product_seller_fk FOREIGN KEY (seller_id)
        REFERENCES seller (seller_id)
        ON DELETE RESTRICT ON UPDATE NO ACTION,
    -- Rule: every product must belong to a category (total participation),
    -- so a category in use cannot be removed until its products are moved.
    CONSTRAINT product_category_fk FOREIGN KEY (category_id)
        REFERENCES category (category_id)
        ON DELETE RESTRICT ON UPDATE NO ACTION
);


-- ---------------------------------------------------------------------
-- PRODUCT_VARIANT  (weak entity: key is (product_id, sku))
-- ---------------------------------------------------------------------
CREATE TABLE product_variant (
    product_id      INTEGER       NOT NULL,
    sku             VARCHAR(40)   NOT NULL,
    size            VARCHAR(20),
    color           VARCHAR(30),
    stock_quantity  INTEGER       NOT NULL DEFAULT 0,
    price_override  NUMERIC(10,2),
    CONSTRAINT product_variant_pk PRIMARY KEY (product_id, sku),
    CONSTRAINT product_variant_size_color_uq
        UNIQUE NULLS NOT DISTINCT (product_id, size, color),
    CONSTRAINT product_variant_stock_ck CHECK (stock_quantity >= 0),
    CONSTRAINT product_variant_price_ck CHECK (price_override IS NULL OR price_override >= 0),
    -- Rule: a variant cannot exist without its product (weak entity), so
    -- deleting a product deletes its variants. The RESTRICT on
    -- order_item still blocks the delete for any variant that was sold.
    CONSTRAINT product_variant_product_fk FOREIGN KEY (product_id)
        REFERENCES product (product_id)
        ON DELETE CASCADE ON UPDATE NO ACTION
);


-- ---------------------------------------------------------------------
-- ORDER_HEADER  (ORDER is a reserved word; the customer is reached
-- through the shipping address, per the BCNF decomposition)
-- ---------------------------------------------------------------------
CREATE TABLE order_header (
    order_id      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    address_id    INTEGER       NOT NULL,
    order_date    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    status        VARCHAR(12)   NOT NULL DEFAULT 'pending',
    total_amount  NUMERIC(12,2) NOT NULL DEFAULT 0,
    CONSTRAINT order_header_pk       PRIMARY KEY (order_id),
    CONSTRAINT order_header_total_ck CHECK (total_amount >= 0),
    CONSTRAINT order_header_status_ck
        CHECK (status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled', 'refunded')),
    -- Rule: an order must always show where it shipped and, through the
    -- address, which customer placed it. An address used by an order can
    -- never be deleted; it is retired with is_active = FALSE instead.
    CONSTRAINT order_header_address_fk FOREIGN KEY (address_id)
        REFERENCES address (address_id)
        ON DELETE RESTRICT ON UPDATE NO ACTION
);


-- ---------------------------------------------------------------------
-- ORDER_ITEM
-- ---------------------------------------------------------------------
CREATE TABLE order_item (
    order_item_id  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    order_id       INTEGER       NOT NULL,
    product_id     INTEGER       NOT NULL,
    sku            VARCHAR(40)   NOT NULL,
    quantity       INTEGER       NOT NULL,
    unit_price     NUMERIC(10,2) NOT NULL,
    CONSTRAINT order_item_pk          PRIMARY KEY (order_item_id),
    CONSTRAINT order_item_variant_uq  UNIQUE (order_id, product_id, sku),
    CONSTRAINT order_item_quantity_ck CHECK (quantity > 0),
    CONSTRAINT order_item_price_ck    CHECK (unit_price >= 0),
    -- Rule: order lines are part of their order and have no meaning alone.
    -- Deleting an order (e.g. an abandoned, unpaid one) removes its lines.
    -- Paid orders are protected by the RESTRICT on payment.order_id.
    CONSTRAINT order_item_order_fk FOREIGN KEY (order_id)
        REFERENCES order_header (order_id)
        ON DELETE CASCADE ON UPDATE NO ACTION,
    -- Rule: a variant that has been sold cannot be deleted, so every order
    -- line keeps pointing at what was bought. If a seller renames a SKU,
    -- the new SKU is carried into past order lines automatically.
    CONSTRAINT order_item_variant_fk FOREIGN KEY (product_id, sku)
        REFERENCES product_variant (product_id, sku)
        ON DELETE RESTRICT ON UPDATE CASCADE
);


-- ---------------------------------------------------------------------
-- PAYMENT
-- ---------------------------------------------------------------------
CREATE TABLE payment (
    payment_id      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    order_id        INTEGER       NOT NULL,
    amount          NUMERIC(12,2) NOT NULL,
    payment_date    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    payment_method  VARCHAR(20)   NOT NULL,
    status          VARCHAR(12)   NOT NULL DEFAULT 'pending',
    CONSTRAINT payment_pk        PRIMARY KEY (payment_id),
    CONSTRAINT payment_amount_ck CHECK (amount > 0),
    CONSTRAINT payment_method_ck
        CHECK (payment_method IN ('card', 'paypal', 'bank_transfer', 'gift_card')),
    CONSTRAINT payment_status_ck
        CHECK (status IN ('pending', 'completed', 'failed', 'refunded')),
    -- Rule: payments are financial records that must be kept. An order
    -- with any payment cannot be deleted; it is cancelled or refunded
    -- through its status instead.
    CONSTRAINT payment_order_fk FOREIGN KEY (order_id)
        REFERENCES order_header (order_id)
        ON DELETE RESTRICT ON UPDATE NO ACTION
);


-- ---------------------------------------------------------------------
-- REVIEW
-- ---------------------------------------------------------------------
CREATE TABLE review (
    review_id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    customer_id  INTEGER     NOT NULL,
    product_id   INTEGER     NOT NULL,
    rating       SMALLINT    NOT NULL,
    comment      TEXT,
    review_date  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT review_pk                  PRIMARY KEY (review_id),
    CONSTRAINT review_customer_product_uq UNIQUE (customer_id, product_id),
    CONSTRAINT review_rating_ck           CHECK (rating BETWEEN 1 AND 5),
    -- Rule: a review belongs to the customer who wrote it. When a customer
    -- account is deleted, their reviews are deleted with it.
    CONSTRAINT review_customer_fk FOREIGN KEY (customer_id)
        REFERENCES customer (customer_id)
        ON DELETE CASCADE ON UPDATE NO ACTION,
    -- Rule: a review is about one product. If an unsold product is removed
    -- from the catalog, its reviews are removed too.
    CONSTRAINT review_product_fk FOREIGN KEY (product_id)
        REFERENCES product (product_id)
        ON DELETE CASCADE ON UPDATE NO ACTION
);


-- ---------------------------------------------------------------------
-- Indexes on foreign-key columns
-- PostgreSQL does not index foreign keys automatically. These indexes
-- speed up joins and the checks run by RESTRICT/CASCADE on delete.
-- (Foreign keys that lead a PK or UNIQUE index are already covered:
--  product_variant.product_id, order_item.order_id, review.customer_id.)
-- ---------------------------------------------------------------------
CREATE INDEX address_customer_idx     ON address      (customer_id);
CREATE INDEX product_seller_idx       ON product      (seller_id);
CREATE INDEX product_category_idx     ON product      (category_id);
CREATE INDEX order_header_address_idx ON order_header (address_id);
CREATE INDEX order_item_variant_idx   ON order_item   (product_id, sku);
CREATE INDEX payment_order_idx        ON payment      (order_id);
CREATE INDEX review_product_idx       ON review       (product_id);
